[project]
name = "insight"
version = "0.1.0.dev0"
description = "InsightPkg is a lightweight Python tool that fetches and aggregates real-time metadata and statistics for open-source Python packages from both PyPI and GitHub."
authors = [{name = "Parth Rathod"}]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
keywords = [ "pypi", "github", "analytics", "reddit" ]
classifiers = ["Topic :: Software Development :: Build Tools"]

[project.urls]
repository = "https://github.com/ParthDevWorks/insightpkg"

[tool.poetry]
packages = [{include = "insight"}]

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
requests = "^2.32.4"
psycopg2-binary = "^2.9.10"
pydantic = "^2.11.7"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
ipykernel = "^6.29.5"
pytest-cov = "^6.2.1"

[tool.poetry.scripts]
pypi_ingest="insight.cli.run:main"

[tool.pytest.ini_options]
addopts = "-v --show-capture=stdout --cov=insight"
testpaths = ["tests/"]

[tool.coverage.report]
skip_empty = true
show_missing = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
