name: Daily Ingest PyPI Data to Supabase

on:
  schedule:
    - cron: '50 23 * * *'  # 11:50 PM UTC = 5:50 PM CST (UTC-6)
  workflow_dispatch:      # Allows manual triggering

env:
    PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
    POETRY_VERSION: ${{ vars.POETRY_VERSION }}
    CONFIG_INI_FILE_PATH: ${{ github.workspace }}/config.ini

jobs:
  run-daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Python and Poetry
        uses: ParthDevWorks/development-actions/actions/install-python-poetry@main
        with:
            python-version: ${{ env.PYTHON_VERSION }}
            poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install project
        run: poetry install --no-interaction
      
      - name: Create config.ini File
        run: |
          cat <<EOF > "$CONFIG"
          [prod]
          db_host=${{ secrets.SUPABASE_DB_HOST }}
          db_database_name=${{ secrets.SUPABASE_DB_NAME }}
          db_port=${{ secrets.SUPABASE_DB_PORT }}
          db_user=${{ secrets.SUPABASE_DB_USER }}
          db_password=${{ secrets.SUPABASE_DB_PASSWORD }}
          EOF

      - name: Run the Ingestion of PyPI to Supabase
        run: poetry run pypi_ingest --store --mode prod