name: Daily Ingest PyPI Data to Supabase

on:
  workflow_dispatch:      # Allows manual triggering
  schedule:
    - cron: "48 23 * * *"  # 11:48 PM UTC = 6:48 PM CST (UTC-6)
  

env:
    PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
    POETRY_VERSION: ${{ vars.POETRY_VERSION }}
    CONFIG_INI_FILE_PATH: ${{ github.workspace }}/config.ini
    LOG_DIR: ${{ github.workspace }}/logs

jobs:
  run-daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Python and Poetry
        uses: ParthDevWorks/development-actions/actions/install-python-poetry@main
        with:
            python-version: ${{ env.PYTHON_VERSION }}
            poetry-version: ${{ env.POETRY_VERSION }}

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.POETRY_VENV_PATH }}
          key: poetry-deps-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
    
      - name: Install Dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction 
      
      - name: Create config.ini File
        run: |
          cat <<EOF > "$CONFIG_INI_FILE_PATH"
          [prod]
          db_host=${{ secrets.SUPABASE_DB_HOST }}
          db_database_name=${{ secrets.SUPABASE_DB_NAME }}
          db_port=${{ secrets.SUPABASE_DB_PORT }}
          db_user=${{ secrets.SUPABASE_DB_USER }}
          db_password=${{ secrets.SUPABASE_DB_PASSWORD }}
          EOF

      - name: Run the Ingestion of PyPI to Supabase
        id: ingest_pypi
        run: poetry run insight --store --mode prod
        continue-on-error: true
      
      - name: Get date
        id: date
        run: echo "name=build-logs-$(date +'%d-%M-%Y')" >> $GITHUB_OUTPUT
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.date.outputs.name }}
          path: ${{ env.LOG_DIR }}
      
      - name: Check If Ingestion Failed
        if: steps.ingest_pypi.outcome == 'failure'
        run: exit 1